### ISSUE TITLE
Can't find variable: admwl

### ISSUE THREAD

**Issue by shahafabileah** [tlk/window.onerror-blacklist#1]
I'm seeing one of your blacklisted error messages on my site: `Can't find variable: admwl`

Out of curiosity, do you know what causes this error?  How do you know that it's safe to include in the blacklist and to ignore?

thanks!

--S

**Comment by tlk** [comment]
Sorry, I don't know what caused that error.

I used this procedure:
Let t1 and t2 be the start and end time of your log-files, then search all the javascript files that have been served from your site during that period. You can do `grep -r admwl .` in your javascript source code directory to find occurrences, and if you have minified/compressed/uglify'ed javascript then include that as well.
